delete from template_lessons;
delete from students;
delete from groups;
delete from courses;
delete from teachers;
delete from audiences;
delete from time_slots;
delete from week_days;
delete from periods;